### PR TITLE
added support for cpp, cxx extensions and their header files (h, hpp, ...

### PR DESCRIPTION
**Pull request by Liamsi**
sloc also supports these extensions: https://github.com/flosse/sloc/pull/50

### CODE REVIEW

**Comment by mark-hahn** [comment]
Thanks.

**Comment by mark-hahn** [comment]
Released in 0.2.0

**Comment by Liamsi** [comment]
Thank you, too! 
But this will only work properly for everyone if sloc builds a new releases which supports theses extensions, too packages.json in line-count gets updated to this (not yet released) version. Currently your addon will show "Warning: File extension 'cxx' is not supported". (Before that it would just ignore these files). I will create anoter pull request, when a new sloc version is released.

**Comment by mark-hahn** [comment]
Ah, I just remembered I had to do a PR to sloc before.  What a pain.  I
wonder if I could patch sloc on the fly or replace it.

**Comment by Liamsi** [comment]
You could, but as it does not really break anything (ok some warnings) I would just wait for the next release of sloc.

**Pull request merged**
