### PR TITLE
Added .ld file support

### PR DESCRIPTION
**Pull request by Towtow10**
GNU linker scripting.

### CODE REVIEW

**Comment by mark-hahn** [comment]
I've merged the commit but there won't be a new version on atom.io until  someone takes over the project.

**Comment by Towtow10** [comment]
I would happily take over.

**Comment by mark-hahn** [comment]
Thanks!  All you have to do is make sure you don't have any repos with the
same name, which happens if you fork it.  Let me know when this is done and
I'll transfer ownership to you.

**Comment by Towtow10** [comment]
My fork has been deleted.

**Comment by mark-hahn** [comment]
It's all yours.  I'm not sure how to change ownership on atom.io.  At the
worst you will have to enter it as a new package.  Ask on the forum.

**Comment by Towtow10** [comment]
ok, ill have a look.

**Comment by Towtow10** [comment]
It looks like you just have to publish a new version with updated json file. 
http://flight-manual.atom.io/behind-atom/sections/maintaining-your-packages/#transferring-ownership
Ill update the json now, after that you will need to publish the new version to atom.io.

**Comment by Towtow10** [comment]
Ok its been updated all you need to do now is update the atom.io package.

**Pull request merged**
