### PR TITLE
Update sloc package to version 0.1.10

### PR DESCRIPTION
**Pull request by ejmsoftware**
I updated the sloc package to version 0.1.10 in order to increase the supported languages.

### CODE REVIEW

**Comment by mark-hahn** [comment]
Thanks.  Merged in 0.5.0

**Comment by SimplyY** [comment]
but apm can't install new version, wish you  publish it

**Comment by mark-hahn** [comment]
Sorry.  I just published it now.

**Comment by SimplyY** [comment]
thank you

**Pull request merged**
